### ISSUE TITLE
the demo doesn't recognize songs

### ISSUE THREAD

**Issue by vjshaddow** [BayernMuller/vibra-live-demo#1]
i always get the same result after a few seconds "Please reduce the surrounding noise and try again"

**Comment by BayernMuller** [comment]
@vjshaddow Hi, thank you for your interest in my project.

As `vibra-web-demo` runs in the browser, permissions are important. Please check if your browser has asked for microphone permissions and if so, have you allowed it.

Also, some microphones (e.g. laptop microphones) perform worse than others or are more susceptible to noise.

If everything looks good, try using the [CLI version](https://github.com/BayernMuller/vibra) to check it out. Thank you!
